const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const { describeOcr, createAnalyzer } = require('../../src/vision/arknights');
const raw = text => ({ text, width: 800, height: 600 });
const jpeg = Buffer.from([255,216,255,0,0,0,0,0,0,0,0,0]);
(async () => {
  assert.equal(describeOcr(raw('终 端 干 员 基 建')).scene, 'home');
  assert.equal(describeOcr(raw('终端')).scene, 'unknown');
  assert.equal(describeOcr(raw('终端 干员 开始行动 代理指挥')).scene, 'unknown');
  assert.equal(describeOcr(raw('行动结束 获得奖励')).verified, false);
  assert.throws(() => describeOcr({ text: 'a' }));
  let release, file;
  const analyze = createAnalyzer({ recognize: async filePath => { file = filePath; return new Promise(resolve => { release = resolve; }); } });
  await assert.rejects(analyze(Buffer.from('invalid image')), /PNG/);
  const cancellation = new AbortController();
  const pending = analyze(jpeg, cancellation.signal);
  while (!release) await new Promise(resolve => setImmediate(resolve));
  await assert.rejects(analyze(jpeg), e => e.statusCode === 409);
  cancellation.abort();
  release(raw('终端 干员'));
  await assert.rejects(pending, e => e.name === 'AbortError');
  await assert.rejects(fs.stat(file), e => e.code === 'ENOENT');
  const next = analyze(jpeg);
  const previous = file;
  while (file === previous) await new Promise(resolve => setImmediate(resolve));
  release(raw('hello'));
  assert.equal((await next).scene, 'unknown');
  console.log('Arknights OCR wrapper: evidence, ambiguity, input checks, single flight, cancellation and temp cleanup passed.');
})().catch(error => { console.error(error); process.exitCode = 1; });
